version: "3"


services:
  web:
    hostname: django
    image: docker.wondergarden.net/alpine-python-devc:latest
    environment:
      - VIRTUAL_PORT=8000
      - VIRTUAL_HOST=lsi.equipment.net
      - LETSENCRYPT_HOST=lsi.equipment.net
    expose:
      - 8000
    ports:
      - 5678:5678
    networks:
      - proxy_network
    volumes:
      - ../..:/workspace:cached
      - django_media:/django_media
      - vhost:/vhost

  proxy:
    image: nginxproxy/nginx-proxy
    labels:
      - com.github.nginx-proxy.nginx
    ports:
      - "80:80"
      - "443:443"     
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - django_media:/etc/nginx/media:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - proxy_network

  acme-companion:
    image: docker.wondergarden.net/acme-companion
    volumes_from:
      - proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - ACME_CA_URI=https://192.168.0.56:8443/acme/acme/directory
      - CERTS_UPDATE_INTERVAL=120
      - RENEW_TIME=+12h
    networks:
      - proxy_network
    #restart: always
  
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
  django_media:

networks:
  proxy_network:
    driver: bridge
